# Generated by Django 4.0.3 on 2022-03-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_category_course_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
